export const templateKeyTypeMap: { [key: string]: 'text' | 'number' | 'select' | 'checkbox' | 'textarea' } = {
  INCOTERM_LOCATION_EN: 'text',
  INCOTERM_LOCATION: 'text',
  QUALITY: 'text',
  QUALITY_EN: 'text',
  PACKAGING: 'text',
  PACKAG_EN: 'text',
  MARKING: 'text',
  MARKING_EN: 'text',
  PORT_OF_LOADING: 'text',
  PORT_OF_DISCHARGE_EN: 'text',

  PARTIAL_DELIVERY: 'select',
  PARTIAL_DELIVERY_EN: 'select',
  TRANSSHIPMENT: 'select',
  TRANSSHIPMENT_EN: 'select',

  DOCUMENT_SENDING_DAYS: 'number',
  BILL_OF_LADING: 'text',
  BILL_OF_LADING_EN: 'text',
  ON_BEHALF_OF: 'text',
  ON_BEHALF_OF_EN: 'text',
  SIGNED_INVOICE_COUNT: 'number',
  PACKING_LIST_DETAIL_COUNT: 'number',
  QUALITY_CERTIFICATE_COUNT: 'number',

  IS_SHOW_LOT_NUMBER: 'checkbox',
  SHOW_LOT_NUMBER_EN: 'checkbox',
  CERTIFICATE_OF_ORIGIN: 'text',
  CERTIFICATE_OF_ORIGIN_EN: 'text',
  AUTHORIZED_LOCATION: 'text',
  AUTHORIZED_LOCATION_EN: 'text',
  ORIGINAL_COPY_COUNT: 'number',
  COPY_COUNT: 'number',
  INSURANCE_AGENT: 'text',
  DOCUMENT_DELIVERY_TIME: 'number',
  CLAIM_FILING_TIME: 'number',
  SELLER_CLAIM_RESPONSE_TIME: 'number',
  QUANTITY_CLAIM_TIME: 'number',
  QUANTITY_SELLER_CLAIM_TIME: 'number',
  WARRANTY_TERMS: 'textarea',
  WARRANTY_TERMS_EN: 'textarea',
  FORCE_MAJEURE_NOTICE_TIME: 'number',
  DISPUTE_RESOLUTION_PLACE: 'text',
  DISPUTE_RESOLUTION_LOCATION_EN: 'text',
  PENALTY_VALUE: 'number',
  PENALTY_PAYMENT_TIME: 'number',
  OTHER_TERMS: 'textarea',
  OTHER_TERMS_EN: 'textarea',
  DELIVERY_POINT: 'text',
  DELIVERY_POINT_EN: 'text',
  DESTINATION: 'text',
  DESTINATION_EN: 'text',
  FREIGHT_PAYMENT_TERM: 'select',
  FREIGHT_PAYMENT_TERM_EN: 'select',

  OTHER_ADDRESS_BUYER: 'text',
  QUALITY_CLAIM_TIME: 'text',
  QUALITY_SELLER_CLAIM_RESPONSE_TIME: 'text',
  ARBITRATION_CENTRE_EN: 'text',
  ARBITRATION_CENTRE_VN: 'text',
  CHAMBER_COMMERCE_NAME_EN: 'text',
  CHAMBER_COMMERCE_NAME_VN: 'text',
};

export const templateKeyFieldMap: { [key: string]: string } = {
  INCOTERM_LOCATION_EN: 'incotermLocationEn',
  INCOTERM_LOCATION: 'incotermLocation2',
  QUALITY: 'quality',
  QUALITY_EN: 'qualityEn',
  PACKAGING: 'packaging',
  PACKAG_EN: 'packagEn',
  MARKING: 'marking',
  MARKING_EN: 'markingEn',
  PORT_OF_LOADING: 'portOfLoading',
  PORT_OF_DISCHARGE_EN: 'portOfDischargeEn',
  PARTIAL_DELIVERY: 'partialDelivery',
  PARTIAL_DELIVERY_EN: 'partialDeliveryEn',
  TRANSSHIPMENT: 'transshipment',
  TRANSSHIPMENT_EN: 'transshipmentEn',
  DOCUMENT_SENDING_DAYS: 'documentSendingDays',
  BILL_OF_LADING: 'billOfLading',
  BILL_OF_LADING_EN: 'billOfLadingEn',
  ON_BEHALF_OF: 'onBehalfOf',
  ON_BEHALF_OF_EN: 'onBehalfOfEn',
  SIGNED_INVOICE_COUNT: 'signedInvoiceCount',
  PACKING_LIST_DETAIL_COUNT: 'packingListDetailCount',
  QUALITY_CERTIFICATE_COUNT: 'qualityCertificateCount',
  IS_SHOW_LOT_NUMBER: 'isShowLot',
  SHOW_LOT_NUMBER_EN: 'isShowLotEn',
  CERTIFICATE_OF_ORIGIN: 'certificateOfOrigin',
  CERTIFICATE_OF_ORIGIN_EN: 'certificateOfOriginEn',
  AUTHORIZED_LOCATION: 'authorizedLocation',
  ORIGINAL_COPY_COUNT: 'originalCopyCount',
  COPY_COUNT: 'copyCount',
  INSURANCE_AGENT: 'insuranceAgent',
  DOCUMENT_DELIVERY_TIME: 'documentDeliveryTime',
  CLAIM_FILING_TIME: 'claimFilingTime',
  SELLER_CLAIM_RESPONSE_TIME: 'sellerClaimResponseTime',
  QUANTITY_CLAIM_TIME: 'quantityClaimTime',
  WARRANTY_TERMS: 'warrantyTerms',
  WARRANTY_TERMS_EN: 'warrantyTermsEn',
  FORCE_MAJEURE_NOTICE_TIME: 'forceMajeureNoticeTime',
  DISPUTE_RESOLUTION_PLACE: 'disputeResolutionPlace',
  DISPUTE_RESOLUTION_LOCATION_EN: 'disputeResolutionLocationEn',
  PENALTY_VALUE: 'penaltyValue',
  PENALTY_PAYMENT_TIME: 'penaltyPaymentTime',
  OTHER_TERMS: 'otherTerms',
  OTHER_TERMS_EN: 'otherTermsEn',
  DELIVERY_POINT: 'deliveryPoint',
  DELIVERY_POINT_EN: 'deliveryPointEn',
  DESTINATION: 'destination',
  DESTINATION_EN: 'destinationEn',
  FREIGHT_PAYMENT_TERM: 'freightPaymentTerm',
  FREIGHT_PAYMENT_TERM_EN: 'freightPaymentTermEn',
  OTHER_ADDRESS_BUYER: 'otherAddressBuyer',
  QUALITY_CLAIM_TIME: 'qualityClaimTime',
  QUALITY_SELLER_CLAIM_RESPONSE_TIME: 'qualitySellerClaimResponseTime',
  ARBITRATION_CENTRE_EN: 'arbitrationCentreEn',
  ARBITRATION_CENTRE_VN: 'arbitrationCentreVn',
  CHAMBER_COMMERCE_NAME_EN: 'chamberCommerceNameEn',
  CHAMBER_COMMERCE_NAME_VN: 'chamberCommerceNameVn',
};

export const templateKeySelectOptionsMap: { [key: string]: { value: any; label: string }[] } = {
  PARTIAL_DELIVERY: [
    { value: 'Allowed', label: 'Cho phép' },
    { value: 'NotAllowed', label: 'Không cho phép' },
  ],
  PARTIAL_DELIVERY_EN: [
    { value: 'Allowed', label: 'Allowed' },
    { value: 'NotAllowed', label: 'Not Allowed' },
  ],
  TRANSSHIPMENT: [
    { value: 'Allowed', label: 'Cho phép' },
    { value: 'NotAllowed', label: 'Không cho phép' },
  ],
  TRANSSHIPMENT_EN: [
    { value: 'Allowed', label: 'Allowed' },
    { value: 'NotAllowed', label: 'Not Allowed' },
  ],
  IS_SHOW_LOT_NUMBER: [
    { value: true, label: 'Hiển thị' },
    { value: false, label: 'Không hiển thị' },
  ],
  FREIGHT_PAYMENT_TERM: [
    { value: 'Prepaid', label: 'Cước phí trả trước' },
    { value: 'Collect', label: 'Cước phí trả sau' },
  ],
  FREIGHT_PAYMENT_TERM_EN: [
    { value: 'Prepaid', label: 'Freight Prepaid' },
    { value: 'Collect', label: 'Freight Collect' },
  ],
};

export const templateKeyFieldLabelMap: { [key: string]: string } = {
  INCOTERM_LOCATION: 'Địa điểm incoterm',
  INCOTERM_LOCATION_EN: 'Địa điểm incoterm (Tiếng Anh)',
  QUALITY: 'Chất lượng',
  QUALITY_EN: 'Chất lượng (Tiếng Anh)',
  PACKAGING: 'Bao bì',
  PACKAG_EN: 'Bao bì (Tiếng Anh)',
  MARKING: 'Ký hiệu đóng gói',
  MARKING_EN: 'Ký hiệu đóng gói (Tiếng Anh)',
  PORT_OF_LOADING: 'Cảng xếp hàng',
  PORT_OF_DISCHARGE_EN: 'Cảng dỡ hàng (Tiếng Anh)',
  PARTIAL_DELIVERY: 'Giao hàng từng phần',
  PARTIAL_DELIVERY_EN: 'Giao hàng từng phần (Tiếng Anh)',
  TRANSSHIPMENT: 'Chuyển tải',
  TRANSSHIPMENT_EN: 'Chuyển tải (Tiếng Anh)',
  DOCUMENT_SENDING_DAYS: 'Số ngày gửi chứng từ',
  BILL_OF_LADING: 'Vận đơn',
  BILL_OF_LADING_EN: 'Vận đơn (Tiếng Anh)',
  ON_BEHALF_OF: 'Thay mặt',
  ON_BEHALF_OF_EN: 'Thay mặt (Tiếng Anh)',
  SIGNED_INVOICE_COUNT: 'Số lượng hóa đơn có chữ ký',
  PACKING_LIST_DETAIL_COUNT: 'Số lượng packing list chi tiết',
  QUALITY_CERTIFICATE_COUNT: 'Số lượng chứng nhận chất lượng',
  IS_SHOW_LOT_NUMBER: 'Hiển thị số lô',
  SHOW_LOT_NUMBER_EN: 'Hiển thị số lô (Tiếng Anh)',
  CERTIFICATE_OF_ORIGIN: 'Giấy chứng nhận xuất xứ',
  CERTIFICATE_OF_ORIGIN_EN: 'Giấy CNXX (Tiếng Anh)',
  AUTHORIZED_LOCATION: 'Địa điểm ủy quyền',
  ORIGINAL_COPY_COUNT: 'Số bản gốc',
  COPY_COUNT: 'Số bản sao',
  INSURANCE_AGENT: 'Đại lý bảo hiểm',
  DOCUMENT_DELIVERY_TIME: 'Thời gian giao chứng từ',
  CLAIM_FILING_TIME: 'Thời gian nộp đơn khiếu nại',
  SELLER_CLAIM_RESPONSE_TIME: 'Thời gian phản hồi khiếu nại từ người bán',
  QUANTITY_CLAIM_TIME: 'Thời gian khiếu nại số lượng',
  WARRANTY_TERMS: 'Điều khoản bảo hành',
  WARRANTY_TERMS_EN: 'Điều khoản bảo hành (Tiếng Anh)',
  FORCE_MAJEURE_NOTICE_TIME: 'Thời gian thông báo bất khả kháng',
  DISPUTE_RESOLUTION_PLACE: 'Địa điểm giải quyết tranh chấp',
  DISPUTE_RESOLUTION_LOCATION_EN: 'Nơi giải quyết tranh chấp (Tiếng Anh)',
  PENALTY_VALUE: 'Giá trị phạt',
  PENALTY_PAYMENT_TIME: 'Thời gian thanh toán phạt',
  OTHER_TERMS: 'Điều khoản khác',
  OTHER_TERMS_EN: 'Điều khoản khác (Tiếng Anh)',
  DELIVERY_POINT: 'Điểm giao hàng',
  DELIVERY_POINT_EN: 'Điểm giao hàng (Tiếng Anh)',
  DESTINATION: 'Điểm đến',
  DESTINATION_EN: 'Điểm đến (Tiếng Anh)',
  FREIGHT_PAYMENT_TERM: 'Điều khoản thanh toán cước',
  FREIGHT_PAYMENT_TERM_EN: 'Điều khoản thanh toán cước (Tiếng Anh)',
  OTHER_ADDRESS_BUYER: 'Địa chỉ khác của bên mua',
  QUALITY_CLAIM_TIME: 'Thời hạn khiếu nại chất lượng',
  QUALITY_SELLER_CLAIM_RESPONSE_TIME: 'Thời hạn phản hồi khiếu nại chất lượng',
  ARBITRATION_CENTRE_EN: 'Trung tâm trọng tài quốc tế (Tiếng Anh)',
  ARBITRATION_CENTRE_VN: 'Trung tâm trọng tài quốc tế (Tiếng Việt)',
  CHAMBER_COMMERCE_NAME_EN: 'Tên phòng thương mại (Tiếng Anh)',
  CHAMBER_COMMERCE_NAME_VN: 'Tên phòng thương mại (Tiếng Việt)',
};
