import { colors } from "~/constants/colors";
import { Module } from "./types";

/** Map từ type (API flow_approve) → cấu hình UI */
export const MODULE_TYPE_CONFIG: Record<
  string,
  Partial<Module> & { navigateFn?: string }
> = {
  PR: {
    title: "PR",
    subtitle: "Purchase Request",
    permissionCode: "PurchaseRequestList",
    icon: "cart",
    iconType: "material-community",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    iconSize: 32,
    navigateFn: "goPR",
  },
  PO: {
    title: "PO",
    subtitle: "Purchase Order",
    permissionCode: "Po",
    icon: "credit-card",
    iconType: "material-community",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    iconSize: 32,
    navigateFn: "goPO",
  },
  BID: {
    title: "Duyệt gói thầu",
    subtitle: "Bid Package",
    permissionCode: "BidNew",
    icon: "shopping-bag",
    iconType: "font-awesome",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    iconSize: 26,
    navigateFn: "goBid",
  },
  SUPPLIER_POTENTIAL: {
    title: "Duyệt NCC",
    permissionCode: "SupplierOfficialUpgrade",
    icon: "account-check",
    iconType: "material-community",
    iconSize: 37,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goSupplierPotential",
  },
  SAP_CODE: {
    title: "Duyệt tạo mã SAP",
    permissionCode: "SupplierCreateCode",
    icon: "database-cog",
    iconType: "material-community",
    iconSize: 32,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goSupplierSap",
  },
  RUSL: {
    title: "Chỉnh sửa pháp lý",
    permissionCode: "ApproveRequestUpdateLawSupplier",
    icon: "file-edit",
    iconType: "material-community",
    iconSize: 29,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goSupplierLaw",
  },
  RUSC: {
    title: "Chỉnh sửa năng lực",
    permissionCode: "ApproveRequestUpdateCapacitySupplier",
    icon: "chart-areaspline",
    iconType: "material-community",
    iconSize: 30,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goSupplierCapacity",
  },
  LS: {
    title: "Khóa/ Mở khóa NCC",
    permissionCode: "ApproveRequestActiveSupplier",
    icon: "account-lock",
    iconType: "material-community",
    iconSize: 36,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goSupplierLock",
  },
  LSS: {
    title: "Khóa/ Mở khóa LVKD",
    permissionCode: "ApproveRequestActiveSupplierService",
    icon: "office-building-cog",
    iconType: "material-community",
    iconSize: 32,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goSupplierLockService",
  },
  USAGE_DEMAND: {
    title: "Nhu cầu sử dụng",
    permissionCode: "Reservation",
    icon: "file-document",
    iconType: "material-community",
    iconSize: 30,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goReservationDemand",
  },
  REPAIR_DEMAND: {
    title: "Nhu cầu sửa chữa",
    permissionCode: "ReservationMaintenance",
    icon: "wrench",
    iconType: "material-community",
    iconSize: 30,
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    navigateFn: "goReservationMaintenance",
  },
  CONTRACT: {
    title: "Duyệt hợp đồng",
    permissionCode: "Contract",
    icon: "file-text",
    iconType: "feather",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    iconSize: 30,
    navigateFn: "goContract",
  },
  SUPPLIER_WIN_BID: {
    title: "NCC thắng thầu",
    permissionCode: "BidRate",
    icon: "award",
    iconType: "feather",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    iconSize: 30,
    navigateFn: "goBidRate",
  },
  MATERIAL_APPROVAL: {
    title: "Lệnh duyệt Material",
    permissionCode: "MaterialApproval",
    icon: "package-variant",
    iconType: "material-community",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    iconSize: 30,
    navigateFn: "goMaterialApproval",
  },
};

/** Nhóm module cha (isGroup = true), con lấy từ API children[] */
export const GROUP_PARENT_TYPES = ["SUPPLIER"];

/** Các type con thuộc SUPPLIER group */
export const SUPPLIER_CHILD_TYPES = [
  "SUPPLIER_POTENTIAL",
  "SAP_CODE",
  "RUSL",
  "RUSC",
  "LS",
  "LSS",
];

export const STATICS_APPROVE_MODULES: Module[] = [
  {
    id: "BUSINESS",
    title: "Duyệt nghiệp vụ",
    subtitle: "Frequently used business functions",
    icon: "briefcase",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    isGroup: true,
    items: [
      {
        title: "PR",
        type: "PR",
        icon: "cart",
        iconType: "material-community",
        iconSize: 32,
        permissionCode: "PurchaseRequestList",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "PO",
        type: "PO",
        icon: "credit-card",
        iconType: "material-community",
        iconSize: 32,
        permissionCode: "Po",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Duyệt gói thầu",
        type: "BID",
        icon: "shopping-bag",
        iconType: "font-awesome",
        iconSize: 26,
        permissionCode: "Bid",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Duyệt hợp đồng",
        type: "CONTRACT",
        icon: "file-text",
        iconType: "feather",
        iconSize: 30,
        permissionCode: "Contract",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "NCC thắng thầu",
        type: "SUPPLIER_WIN_BID",
        icon: "award",
        iconType: "feather",
        iconSize: 30,
        permissionCode: "BidRate",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Nhu cầu sử dụng",
        type: "USAGE_DEMAND_SUB",
        icon: "file-document",
        iconType: "material-community",
        iconSize: 30,
        permissionCode: "Reservation",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Nhu cầu sửa chữa",
        type: "REPAIR_DEMAND",
        icon: "wrench",
        iconType: "material-community",
        iconSize: 30,
        permissionCode: "ReservationMaintenance",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Lệnh duyệt Material",
        type: "MATERIAL_APPROVAL",
        icon: "package-variant",
        iconType: "material-community",
        iconSize: 30,
        permissionCode: "MaterialApproval",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
    ],
  },
  {
    id: "SUPPLIER",
    title: "Nhà cung cấp",
    subtitle: "Supplier",
    permissionCode: "ManagementSupSupplier",
    icon: "users",
    iconContainerColor: colors.goldLight,
    iconColor: colors.brandOrange,
    isGroup: true,
    items: [
      {
        title: "Duyệt NCC",
        type: "SUPPLIER_POTENTIAL",
        icon: "account-check",
        iconType: "material-community",
        iconSize: 37,
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
        permissionCode: "SupplierOfficialUpgrade",
      },
      {
        title: "Duyệt tạo mã SAP",
        type: "SAP_CODE",
        icon: "database-cog",
        iconType: "material-community",
        iconSize: 32,
        permissionCode: "SupplierCreateCode",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Chỉnh sửa pháp lý",
        type: "RUSL",
        icon: "file-edit",
        iconType: "material-community",
        iconSize: 29,
        permissionCode: "ApproveRequestUpdateLawSupplier",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Chỉnh sửa năng lực",
        type: "RUSC",
        icon: "chart-areaspline",
        iconType: "material-community",
        iconSize: 30,
        permissionCode: "ApproveRequestUpdateCapacitySupplier",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Khóa/ Mở khóa NCC",
        type: "LS",
        icon: "account-lock",
        iconType: "material-community",
        iconSize: 36,
        permissionCode: "ApproveRequestActiveSupplier",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
      {
        title: "Khóa/ Mở khóa LVKD",
        type: "LSS",
        icon: "office-building-cog",
        iconType: "material-community",
        iconSize: 32,
        permissionCode: "ApproveRequestActiveSupplierService",
        iconContainerColor: colors.goldLight,
        iconColor: colors.brandOrange,
      },
    ],
  },
];
