import { Bom } from "../features/bom/types";

export const mockBoms: Bom[] = [
  {
    BomId: "BOM-001",
    ItemCode: "FG-001",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-001",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-001",
        BomId: "BOM-001",
        ErpItemCode: "IP-103",
        Selected_SpecId: "SPEC-IP103-V1",
        Selected_SpecCode: "SPEC-IP-103-V1",
      },
      {
        BomLineId: "BOM-LINE-002",
        BomId: "BOM-001",
        ErpItemCode: "RM-202",
        Selected_SpecId: "SPEC-RM202-V1",
        Selected_SpecCode: "SPEC-RM-202",
      },
      {
        BomLineId: "BOM-LINE-003",
        BomId: "BOM-001",
        ErpItemCode: "PG-303",
        Selected_SpecId: "SPEC-PG303-V1",
        Selected_SpecCode: "SPEC-PG-303",
      },
    ],
  },
  {
    BomId: "BOM-002-V1",
    ItemCode: "FG-002",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-001",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-05-31",
    BomLines: [
      {
        BomLineId: "BOM-LINE-002-V1-001",
        BomId: "BOM-002-V1",
        ErpItemCode: "IP-101",
        Selected_SpecId: "SPEC-IP101-V1",
        Selected_SpecCode: "SPEC-IP-101-V1",
      },
    ],
  },
  {
    BomId: "BOM-002",
    ItemCode: "FG-002",
    ErpVersion: "2",
    Version: "2",
    Selected_HscbVersionId: "HSCB-VERSION-002",
    ValidFrom: "2026-02-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-004",
        BomId: "BOM-002",
        ErpItemCode: "IP-101",
        Selected_SpecId: "SPEC-IP101-V1",
        Selected_SpecCode: "SPEC-IP-101-V1",
      },
      {
        BomLineId: "BOM-LINE-005",
        BomId: "BOM-002",
        ErpItemCode: "RM-201",
        Selected_SpecId: "SPEC-RM201-V1",
        Selected_SpecCode: "SPEC-RM-201-V1",
      },
      {
        BomLineId: "BOM-LINE-006",
        BomId: "BOM-002",
        ErpItemCode: "PG-301",
        Selected_SpecId: "SPEC-PG301-V1",
        Selected_SpecCode: "SPEC-PG-301",
      },
    ],
  },
  {
    BomId: "BOM-003",
    ItemCode: "FG-003",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-003",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-031",
        BomId: "BOM-003",
        ErpItemCode: "FG-001",
        Selected_SpecId: "SPEC-FG001-V1",
        Selected_SpecCode: "TCCS-FG-001-V1",
        Selected_HscbVersionId: "HSCB-VERSION-001",
      },
      {
        BomLineId: "BOM-LINE-032",
        BomId: "BOM-003",
        ErpItemCode: "FG-002",
        Selected_SpecId: "SPEC-FG002-V1",
        Selected_SpecCode: "TCCS-FG-002-V1",
        Selected_HscbVersionId: "HSCB-VERSION-002",
      },
      {
        BomLineId: "BOM-LINE-033",
        BomId: "BOM-003",
        ErpItemCode: "PG-302",
        Selected_SpecId: "SPEC-PG302-V1",
        Selected_SpecCode: "SPEC-PG-302",
      },
    ],
  },
  {
    BomId: "BOM-004",
    ItemCode: "FG-004",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-004",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-007",
        BomId: "BOM-004",
        ErpItemCode: "IP-104",
        Selected_SpecId: "SPEC-IP104-V1",
        Selected_SpecCode: "SPEC-IP-104",
      },
      {
        BomLineId: "BOM-LINE-008",
        BomId: "BOM-004",
        ErpItemCode: "RM-204",
        Selected_SpecId: "SPEC-RM204-V1",
        Selected_SpecCode: "SPEC-RM-204",
      },
      {
        BomLineId: "BOM-LINE-009",
        BomId: "BOM-004",
        ErpItemCode: "RM-206",
        Selected_SpecId: "SPEC-SHARED-SALT-SUGAR",
        Selected_SpecCode: "SPEC-SHARED-SALT-SUGAR",
      },
      {
        BomLineId: "BOM-LINE-010",
        BomId: "BOM-004",
        ErpItemCode: "RM-207",
        Selected_SpecId: "SPEC-SHARED-SALT-SUGAR",
        Selected_SpecCode: "SPEC-SHARED-SALT-SUGAR",
      },
      {
        BomLineId: "BOM-LINE-011",
        BomId: "BOM-004",
        ErpItemCode: "PG-304",
        Selected_SpecId: "SPEC-PG304-V1",
        Selected_SpecCode: "SPEC-PG-304",
      },
    ],
  },
  {
    BomId: "BOM-005",
    ItemCode: "FG-005",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-005",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-012",
        BomId: "BOM-005",
        ErpItemCode: "IP-105",
        Selected_SpecId: "SPEC-IP105-V1",
        Selected_SpecCode: "SPEC-IP-105",
      },
      {
        BomLineId: "BOM-LINE-013",
        BomId: "BOM-005",
        ErpItemCode: "RM-203",
        Selected_SpecId: "SPEC-RM203-V1",
        Selected_SpecCode: "SPEC-RM-203",
      },
      {
        BomLineId: "BOM-LINE-014",
        BomId: "BOM-005",
        ErpItemCode: "RM-206",
        Selected_SpecId: "SPEC-RM206-V1",
        Selected_SpecCode: "SPEC-RM-206",
      },
      {
        BomLineId: "BOM-LINE-015",
        BomId: "BOM-005",
        ErpItemCode: "PG-305",
        Selected_SpecId: "SPEC-PG305-V1",
        Selected_SpecCode: "SPEC-PG-305",
      },
      {
        BomLineId: "BOM-LINE-016",
        BomId: "BOM-005",
        ErpItemCode: "PG-306",
        Selected_SpecId: "SPEC-PG306-V1",
        Selected_SpecCode: "SPEC-PG-306",
      },
    ],
  },
  {
    BomId: "BOM-006",
    ItemCode: "FG-007",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-007",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-017",
        BomId: "BOM-006",
        ErpItemCode: "IP-106",
        Selected_SpecId: "SPEC-IP106-V1",
        Selected_SpecCode: "SPEC-IP-106-V1",
      },
      {
        BomLineId: "BOM-LINE-018",
        BomId: "BOM-006",
        ErpItemCode: "RM-204",
        Selected_SpecId: "SPEC-RM204-V1",
        Selected_SpecCode: "SPEC-RM-204",
      },
      {
        BomLineId: "BOM-LINE-019",
        BomId: "BOM-006",
        ErpItemCode: "PG-307",
        Selected_SpecId: "SPEC-PG307-V1",
        Selected_SpecCode: "SPEC-PG-307-V1",
      },
      {
        BomLineId: "BOM-LINE-020",
        BomId: "BOM-006",
        ErpItemCode: "PG-308",
        Selected_SpecId: "SPEC-PG308-V1",
        Selected_SpecCode: "SPEC-PG-308-V1",
      },
    ],
  },
  {
    BomId: "BOM-007",
    ItemCode: "FG-008",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-008",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-021",
        BomId: "BOM-007",
        ErpItemCode: "IP-105",
        Selected_SpecId: "SPEC-IP105-V1",
        Selected_SpecCode: "SPEC-IP-105",
      },
      {
        BomLineId: "BOM-LINE-022",
        BomId: "BOM-007",
        ErpItemCode: "RM-203",
        Selected_SpecId: "SPEC-RM203-V1",
        Selected_SpecCode: "SPEC-RM-203",
      },
      {
        BomLineId: "BOM-LINE-023",
        BomId: "BOM-007",
        ErpItemCode: "PG-305",
        Selected_SpecId: "SPEC-PG305-V1",
        Selected_SpecCode: "SPEC-PG-305",
      },
    ],
  },
  {
    BomId: "BOM-008",
    ItemCode: "FG-009",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-009",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-024",
        BomId: "BOM-008",
        ErpItemCode: "IP-108",
        Selected_SpecId: "SPEC-IP108-V1",
        Selected_SpecCode: "SPEC-IP-108-V1",
      },
      {
        BomLineId: "BOM-LINE-025",
        BomId: "BOM-008",
        ErpItemCode: "RM-206",
        Selected_SpecId: "SPEC-RM206-V1",
        Selected_SpecCode: "SPEC-RM-206",
      },
      {
        BomLineId: "BOM-LINE-026",
        BomId: "BOM-008",
        ErpItemCode: "RM-207",
        Selected_SpecId: "SPEC-RM207-V1",
        Selected_SpecCode: "SPEC-RM-207",
      },
      {
        BomLineId: "BOM-LINE-027",
        BomId: "BOM-008",
        ErpItemCode: "PG-303",
        Selected_SpecId: "SPEC-PG303-V1",
        Selected_SpecCode: "SPEC-PG-303",
      },
    ],
  },
  {
    BomId: "BOM-010",
    ItemCode: "FG-010",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-010",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-028",
        BomId: "BOM-010",
        ErpItemCode: "IP-109",
        Selected_SpecId: "SPEC-IP109-V1",
        Selected_SpecCode: "SPEC-IP-109-V1",
      },
      {
        BomLineId: "BOM-LINE-029",
        BomId: "BOM-010",
        ErpItemCode: "RM-207",
        Selected_SpecId: "SPEC-SHARED-SALT-SUGAR",
        Selected_SpecCode: "SPEC-SHARED-SALT-SUGAR",
      },
      {
        BomLineId: "BOM-LINE-030",
        BomId: "BOM-010",
        ErpItemCode: "PG-309",
        Selected_SpecId: "SPEC-PG309-V1",
        Selected_SpecCode: "SPEC-PG-309-V1",
      },
    ],
  },
  {
    BomId: "BOM-011",
    ItemCode: "FG-011",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "HSCB-VERSION-011",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-041",
        BomId: "BOM-011",
        ErpItemCode: "FG-003",
        Selected_SpecId: "SPEC-FG003-V1",
        Selected_SpecCode: "TCCS-FG-003-V1",
        Selected_HscbVersionId: "HSCB-VERSION-003",
      },
      {
        BomLineId: "BOM-LINE-042",
        BomId: "BOM-011",
        ErpItemCode: "FG-004",
        Selected_SpecId: "SPEC-FG004-V1",
        Selected_SpecCode: "TCCS-FG-004-V1",
        Selected_HscbVersionId: "HSCB-VERSION-004",
      },
      {
        BomLineId: "BOM-LINE-043",
        BomId: "BOM-011",
        ErpItemCode: "FG-007",
        Selected_SpecId: "SPEC-FG007-V1",
        Selected_SpecCode: "TCCS-FG-007-V1",
        Selected_HscbVersionId: "HSCB-VERSION-007",
      },
      {
        BomLineId: "BOM-LINE-044",
        BomId: "BOM-011",
        ErpItemCode: "PG-302",
        Selected_SpecId: "SPEC-PG302-V1",
        Selected_SpecCode: "SPEC-PG-302",
      },
    ],
  },
  {
    BomId: "BOM-006-EMPTY",
    ItemCode: "FG-006",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "",
    ValidFrom: "2026-03-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-051",
        BomId: "BOM-006-EMPTY",
        ErpItemCode: "RM-206",
        Selected_SpecId: "",
        Selected_SpecCode: "",
      },
      {
        BomLineId: "BOM-LINE-052",
        BomId: "BOM-006-EMPTY",
        ErpItemCode: "PG-303",
        Selected_SpecId: "SPEC-PG303-V1",
        Selected_SpecCode: "SPEC-PG-303",
      },
    ],
  },
  {
    BomId: "BOM-IP103-V1",
    ItemCode: "IP-103",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-IP103-001",
        BomId: "BOM-IP103-V1",
        ErpItemCode: "IP-104",
        Selected_SpecId: "SPEC-IP104-V1",
        Selected_SpecCode: "SPEC-IP-104-V1",
      },
      {
        BomLineId: "BOM-LINE-IP103-002",
        BomId: "BOM-IP103-V1",
        ErpItemCode: "RM-204",
        Selected_SpecId: "SPEC-RM204-V1",
        Selected_SpecCode: "SPEC-RM-204",
      },
    ],
  },
  {
    BomId: "BOM-IP104-V1",
    ItemCode: "IP-104",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-IP104-001",
        BomId: "BOM-IP104-V1",
        ErpItemCode: "IP-105",
        Selected_SpecId: "SPEC-IP105-V1",
        Selected_SpecCode: "SPEC-IP-105-V1",
      },
    ],
  },
  {
    BomId: "BOM-IP105-V1",
    ItemCode: "IP-105",
    ErpVersion: "1",
    Version: "1",
    Selected_HscbVersionId: "",
    ValidFrom: "2026-01-01",
    ValidTo: null,
    BomLines: [
      {
        BomLineId: "BOM-LINE-IP105-001",
        BomId: "BOM-IP105-V1",
        ErpItemCode: "RM-205",
        Selected_SpecId: "SPEC-RM205-V1",
        Selected_SpecCode: "SPEC-RM-205-V1",
      },
      {
        BomLineId: "BOM-LINE-IP105-002",
        BomId: "BOM-IP105-V1",
        ErpItemCode: "RM-206",
        Selected_SpecId: "SPEC-RM206-V1",
        Selected_SpecCode: "SPEC-RM-206",
      },
      {
        BomLineId: "BOM-LINE-IP105-003",
        BomId: "BOM-IP105-V1",
        ErpItemCode: "PG-304",
        Selected_SpecId: "SPEC-PG304-V1",
        Selected_SpecCode: "SPEC-PG-304",
      },
    ],
  },
];
