import { Doc, DocStatus, DocType } from "../features/doc/types";

export const mockDocs: Doc[] = [
  // ==========================================
  // 1. COA (5 items)
  // ==========================================
  {
    DocId: "DOC-001",
    PartnerId: "PARTNER-001",
    DocCode: "COA-RM201-2026",
    Version: "1",
    DocType: DocType.COA,
    DocName: "Chung nhan COA - Hanh la say kho",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-001", DocId: "DOC-001", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-002",
    PartnerId: "PARTNER-002",
    DocCode: "COA-RM202-2026",
    Version: "1",
    DocType: DocType.COA,
    DocName: "Chung nhan COA - Ot tuoi chi thien",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-002", DocId: "DOC-002", ItemCode: "RM-202" },
    ],
  },
  {
    DocId: "DOC-003",
    PartnerId: "PARTNER-004",
    DocCode: "COA-RM203-2026",
    Version: "1",
    DocType: DocType.COA,
    DocName: "Chung nhan COA - Bot mi cao cap nhap khau",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-003", DocId: "DOC-003", ItemCode: "RM-203" },
    ],
  },
  {
    DocId: "DOC-004",
    PartnerId: "PARTNER-008",
    DocCode: "COA-RM204-2026",
    Version: "1",
    DocType: DocType.COA,
    DocName: "Chung nhan COA - Toi Ly Son sach vo",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-004", DocId: "DOC-004", ItemCode: "RM-204" },
    ],
  },
  {
    DocId: "DOC-005",
    PartnerId: "PARTNER-010",
    DocCode: "COA-RM208-2026",
    Version: "1",
    DocType: DocType.COA,
    DocName: "Chung nhan COA - Ca chua tuoi huu co",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-005", DocId: "DOC-005", ItemCode: "RM-208" },
    ],
  },

  // ==========================================
  // 2. SPECIFICATION (5 items)
  // ==========================================
  {
    DocId: "DOC-006",
    PartnerId: "PARTNER-003",
    DocCode: "SPEC-PG303-2026",
    Version: "1",
    DocType: DocType.SPECIFICATION,
    DocName: "Tieu chuan ky thuat - Vo chai PET 250ml",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-02-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-006", DocId: "DOC-006", ItemCode: "PG-303" },
    ],
  },
  {
    DocId: "DOC-007",
    PartnerId: "PARTNER-005",
    DocCode: "SPEC-PG301-2026",
    Version: "1",
    DocType: DocType.SPECIFICATION,
    DocName: "Tieu chuan ky thuat - Mang co OPP boc goi mi",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-007", DocId: "DOC-007", ItemCode: "PG-301" },
    ],
  },
  {
    DocId: "DOC-008",
    PartnerId: "PARTNER-007",
    DocCode: "SPEC-RM207-2026",
    Version: "1",
    DocType: DocType.SPECIFICATION,
    DocName: "Tieu chuan chat luong - Duong tinh luyen Bien Hoa",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-008", DocId: "DOC-008", ItemCode: "RM-207" },
    ],
  },
  {
    DocId: "DOC-009",
    PartnerId: "PARTNER-009",
    DocCode: "SPEC-PG309-2026",
    Version: "1",
    DocType: DocType.SPECIFICATION,
    DocName: "Tieu chuan ky thuat - Lon nhom chao Minh Trung",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-009", DocId: "DOC-009", ItemCode: "PG-309" },
    ],
  },
  {
    DocId: "DOC-010",
    PartnerId: "PARTNER-015",
    DocCode: "SPEC-PG310-2026",
    Version: "1",
    DocType: DocType.SPECIFICATION,
    DocName: "Tieu chuan - Mang nhom phuc hop tui hat nem",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-010", DocId: "DOC-010", ItemCode: "PG-310" },
    ],
  },

  // ==========================================
  // 3. HSCB (5 items)
  // ==========================================
  {
    DocId: "DOC-011",
    PartnerId: "PARTNER-001",
    DocCode: "HSCB-RM201-2026",
    Version: "1",
    DocType: DocType.HSCB,
    DocName: "Ho so cong bo hop chuan - Hanh say kho",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-011", DocId: "DOC-011", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-012",
    PartnerId: "PARTNER-002",
    DocCode: "HSCB-RM202-2026",
    Version: "1",
    DocType: DocType.HSCB,
    DocName: "Ho so cong bo - Ot tuoi sach Da Lat",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-012", DocId: "DOC-012", ItemCode: "RM-202" },
    ],
  },
  {
    DocId: "DOC-013",
    PartnerId: "PARTNER-003",
    DocCode: "HSCB-PG303-2026",
    Version: "1",
    DocType: DocType.HSCB,
    DocName: "Ho so cong bo - Chai PET dung nuoc tuong",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-013", DocId: "DOC-013", ItemCode: "PG-303" },
    ],
  },
  {
    DocId: "DOC-014",
    PartnerId: "PARTNER-004",
    DocCode: "HSCB-RM203-2026",
    Version: "1",
    DocType: DocType.HSCB,
    DocName: "Ho so tu cong bo chat luong - Bot mi",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-014", DocId: "DOC-014", ItemCode: "RM-203" },
    ],
  },
  {
    DocId: "DOC-015",
    PartnerId: "PARTNER-005",
    DocCode: "HSCB-PG301-2026",
    Version: "1",
    DocType: DocType.HSCB,
    DocName: "Ho so cong bo san pham - Mang co OPP boc mi",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-015", DocId: "DOC-015", ItemCode: "PG-301" },
    ],
  },

  // ==========================================
  // 4. TCCS (5 items)
  // ==========================================
  {
    DocId: "DOC-016",
    PartnerId: "PARTNER-006",
    DocCode: "TCCS-IP101-2026",
    Version: "1",
    DocType: DocType.TCCS,
    DocName: "Tieu chuan Co so BTP - Nuoc cot xuong bo",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-10",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-016", DocId: "DOC-016", ItemCode: "IP-101" },
    ],
  },
  {
    DocId: "DOC-017",
    PartnerId: "PARTNER-008",
    DocCode: "TCCS-RM204-2026",
    Version: "1",
    DocType: DocType.TCCS,
    DocName: "Tieu chuan Co so - Toi Ly Son say gion",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-017", DocId: "DOC-017", ItemCode: "RM-204" },
    ],
  },
  {
    DocId: "DOC-018",
    PartnerId: "PARTNER-012",
    DocCode: "TCCS-RM210-2026",
    Version: "1",
    DocType: DocType.TCCS,
    DocName: "Tieu chuan Co so - Hat sen tuoi Dong Thap",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-018", DocId: "DOC-018", ItemCode: "RM-210" },
    ],
  },
  {
    DocId: "DOC-019",
    PartnerId: "PARTNER-014",
    DocCode: "TCCS-RM214-2026",
    Version: "1",
    DocType: DocType.TCCS,
    DocName: "Tieu chuan Co so - Ca com tuoi dai duong",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-019", DocId: "DOC-019", ItemCode: "RM-214" },
    ],
  },
  {
    DocId: "DOC-020",
    PartnerId: "PARTNER-016",
    DocCode: "TCCS-RM213-2026",
    Version: "1",
    DocType: DocType.TCCS,
    DocName: "Tieu chuan Co so - Chat dieu chinh Acid Citric",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-020", DocId: "DOC-020", ItemCode: "RM-213" },
    ],
  },

  // ==========================================
  // 5. DI_UNG (5 items - Excel Template files)
  // ==========================================
  {
    DocId: "DOC-021",
    PartnerId: "PARTNER-001",
    DocCode: "DIUNG-RM201-2026",
    Version: "1",
    DocType: DocType.DI_UNG,
    DocName: "Khau bao di ung - Hanh la say kho",
    FileURL: "/files/Template_Allergen.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-021", DocId: "DOC-021", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-022",
    PartnerId: "PARTNER-008",
    DocCode: "DIUNG-RM202-2026",
    Version: "1",
    DocType: DocType.DI_UNG,
    DocName: "Bao cao di ung - Ot tuoi sach",
    FileURL: "/files/Template_Allergen.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-022", DocId: "DOC-022", ItemCode: "RM-202" },
    ],
  },
  {
    DocId: "DOC-023",
    PartnerId: "PARTNER-007",
    DocCode: "DIUNG-RM203-2026",
    Version: "1",
    DocType: DocType.DI_UNG,
    DocName: "Khai bao di ung - Bot mi cao cap",
    FileURL: "/files/Template_Allergen.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-023", DocId: "DOC-023", ItemCode: "RM-203" },
    ],
  },
  {
    DocId: "DOC-024",
    PartnerId: "PARTNER-011",
    DocCode: "DIUNG-RM201-V2",
    Version: "2",
    DocType: DocType.DI_UNG,
    DocName: "Khai bao di ung cap nhat - Hanh say kho",
    FileURL: "/files/Template_Allergen.xlsx",
    ValidFrom: "2026-05-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-024", DocId: "DOC-024", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-025",
    PartnerId: "PARTNER-013",
    DocCode: "DIUNG-RM209-2026",
    Version: "1",
    DocType: DocType.DI_UNG,
    DocName: "Khai bao di ung - Tieu den Phu Quoc",
    FileURL: "/files/Template_Allergen.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-025", DocId: "DOC-025", ItemCode: "RM-209" },
    ],
  },

  // ==========================================
  // 6. DINH_DUONG (5 items - Excel Template files)
  // ==========================================
  {
    DocId: "DOC-026",
    PartnerId: "PARTNER-001",
    DocCode: "NUTR-RM201-2026",
    Version: "1",
    DocType: DocType.DINH_DUONG,
    DocName: "Bang gia tri dinh duong - Hanh la say kho",
    FileURL: "/files/Template_Nutrition.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-026", DocId: "DOC-026", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-027",
    PartnerId: "PARTNER-008",
    DocCode: "NUTR-RM204-2026",
    Version: "1",
    DocType: DocType.DINH_DUONG,
    DocName: "Thong tin dinh duong - Toi Ly Son",
    FileURL: "/files/Template_Nutrition.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-027", DocId: "DOC-027", ItemCode: "RM-204" },
    ],
  },
  {
    DocId: "DOC-028",
    PartnerId: "PARTNER-007",
    DocCode: "NUTR-RM207-2026",
    Version: "1",
    DocType: DocType.DINH_DUONG,
    DocName: "Bang phan tich dinh duong - Duong Bien Hoa",
    FileURL: "/files/Template_Nutrition.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-028", DocId: "DOC-028", ItemCode: "RM-207" },
    ],
  },
  {
    DocId: "DOC-029",
    PartnerId: "PARTNER-012",
    DocCode: "NUTR-RM210-2026",
    Version: "1",
    DocType: DocType.DINH_DUONG,
    DocName: "Thong tin ham luong dinh duong - Hat sen tươi",
    FileURL: "/files/Template_Nutrition.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-029", DocId: "DOC-029", ItemCode: "RM-210" },
    ],
  },
  {
    DocId: "DOC-030",
    PartnerId: "PARTNER-014",
    DocCode: "NUTR-RM211-2026",
    Version: "1",
    DocType: DocType.DINH_DUONG,
    DocName: "Thong tin dinh duong - Bot tom su say kho",
    FileURL: "/files/Template_Nutrition.xlsx",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-030", DocId: "DOC-030", ItemCode: "RM-211" },
    ],
  },

  // ==========================================
  // 7. HDSD (5 items)
  // ==========================================
  {
    DocId: "DOC-031",
    PartnerId: "PARTNER-001",
    DocCode: "HDSD-RM201-2026",
    Version: "1",
    DocType: DocType.HDSD,
    DocName: "Huong dan su dung - Hanh la say kho",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-031", DocId: "DOC-031", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-032",
    PartnerId: "PARTNER-003",
    DocCode: "HDSD-PG303-2026",
    Version: "1",
    DocType: DocType.HDSD,
    DocName: "Huong dan su dung / Kien nghi vo chai PET",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-032", DocId: "DOC-032", ItemCode: "PG-303" },
    ],
  },
  {
    DocId: "DOC-033",
    PartnerId: "PARTNER-005",
    DocCode: "HDSD-PG301-2026",
    Version: "1",
    DocType: DocType.HDSD,
    DocName: "Huong dan can chinh may boc mang co OPP",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-033", DocId: "DOC-033", ItemCode: "PG-301" },
    ],
  },
  {
    DocId: "DOC-034",
    PartnerId: "PARTNER-007",
    DocCode: "HDSD-RM207-2026",
    Version: "1",
    DocType: DocType.HDSD,
    DocName: "Huong dan su dung duong trong che bien thuc pham",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-034", DocId: "DOC-034", ItemCode: "RM-207" },
    ],
  },
  {
    DocId: "DOC-035",
    PartnerId: "PARTNER-011",
    DocCode: "HDSD-RM201-V2",
    Version: "2",
    DocType: DocType.HDSD,
    DocName: "Huong dan pha do tron huong hoa anh dao",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-035", DocId: "DOC-035", ItemCode: "RM-201" },
    ],
  },

  // ==========================================
  // 8. HD_BAO_QUAN (5 items)
  // ==========================================
  {
    DocId: "DOC-036",
    PartnerId: "PARTNER-001",
    DocCode: "HDBQ-RM201-2026",
    Version: "1",
    DocType: DocType.HD_BAO_QUAN,
    DocName: "Huong dan bao quan hanh la say kho o nhiet do phong",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-036", DocId: "DOC-036", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-037",
    PartnerId: "PARTNER-002",
    DocCode: "HDBQ-RM202-2026",
    Version: "1",
    DocType: DocType.HD_BAO_QUAN,
    DocName: "Huong dan bao quan lanh dong - Ot tuoi sach",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-037", DocId: "DOC-037", ItemCode: "RM-202" },
    ],
  },
  {
    DocId: "DOC-038",
    PartnerId: "PARTNER-004",
    DocCode: "HDBQ-RM203-2026",
    Version: "1",
    DocType: DocType.HD_BAO_QUAN,
    DocName: "Huong dan bao quan tranh am uot - Bot mi nhap khau",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-038", DocId: "DOC-038", ItemCode: "RM-203" },
    ],
  },
  {
    DocId: "DOC-039",
    PartnerId: "PARTNER-008",
    DocCode: "HDBQ-RM204-2026",
    Version: "1",
    DocType: DocType.HD_BAO_QUAN,
    DocName: "Yeu cau bao quan kho rao - Toi kho Ly Son",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-039", DocId: "DOC-039", ItemCode: "RM-204" },
    ],
  },
  {
    DocId: "DOC-040",
    PartnerId: "PARTNER-010",
    DocCode: "HDBQ-RM208-2026",
    Version: "1",
    DocType: DocType.HD_BAO_QUAN,
    DocName: "Quy trinh bao quan mat nhiet do thap - Ca chua",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-040", DocId: "DOC-040", ItemCode: "RM-208" },
    ],
  },

  // ==========================================
  // 9. CERTIFICATE (5 items)
  // ==========================================
  {
    DocId: "DOC-041",
    PartnerId: "PARTNER-001",
    DocCode: "CERT-NCC001-2026",
    Version: "1",
    DocType: DocType.CERTIFICATE,
    DocName: "Chung chi ISO 22000 - Cung cap Gia vi VN",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-041", DocId: "DOC-041", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-042",
    PartnerId: "PARTNER-003",
    DocCode: "CERT-NCC003-2026",
    Version: "1",
    DocType: DocType.CERTIFICATE,
    DocName: "Chung nhan an toan nguyen lieu - Nhua Thanh Phat",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-042", DocId: "DOC-042", ItemCode: "PG-303" },
    ],
  },
  {
    DocId: "DOC-043",
    PartnerId: "PARTNER-005",
    DocCode: "CERT-NCC005-2026",
    Version: "1",
    DocType: DocType.CERTIFICATE,
    DocName: "Chung chi HACCP - Bao bi Minh Phat",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-043", DocId: "DOC-043", ItemCode: "PG-301" },
    ],
  },
  {
    DocId: "DOC-044",
    PartnerId: "PARTNER-007",
    DocCode: "CERT-NCC007-2026",
    Version: "1",
    DocType: DocType.CERTIFICATE,
    DocName: "Chung chi HALAL - Duong cat Khanh Hoa",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-044", DocId: "DOC-044", ItemCode: "RM-207" },
    ],
  },
  {
    DocId: "DOC-045",
    PartnerId: "PARTNER-015",
    DocCode: "CERT-NCC015-2026",
    Version: "1",
    DocType: DocType.CERTIFICATE,
    DocName: "Chung nhan ISO 9001 - Mang nhom Hai Phong",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-045", DocId: "DOC-045", ItemCode: "PG-310" },
    ],
  },

  // ==========================================
  // 10. CO_KQKN (5 items)
  // ==========================================
  {
    DocId: "DOC-046",
    PartnerId: "PARTNER-004",
    DocCode: "CO-RM203-2026",
    Version: "1",
    DocType: DocType.CO_KQKN,
    DocName: "Chung nhan xuat xu C/O - Bot mi Cau Tre",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-046", DocId: "DOC-046", ItemCode: "RM-203" },
    ],
  },
  {
    DocId: "DOC-047",
    PartnerId: "PARTNER-007",
    DocCode: "CO-RM207-2026",
    Version: "1",
    DocType: DocType.CO_KQKN,
    DocName: "Ket qua kiem nghiem chat luong - Duong Khanh Hoa",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-047", DocId: "DOC-047", ItemCode: "RM-207" },
    ],
  },
  {
    DocId: "DOC-048",
    PartnerId: "PARTNER-010",
    DocCode: "CO-RM208-2026",
    Version: "1",
    DocType: DocType.CO_KQKN,
    DocName: "Phan tich kim loai nang - Ca chua Lam Dong",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-048", DocId: "DOC-048", ItemCode: "RM-208" },
    ],
  },
  {
    DocId: "DOC-049",
    PartnerId: "PARTNER-013",
    DocCode: "CO-RM209-2026",
    Version: "1",
    DocType: DocType.CO_KQKN,
    DocName: "Ket qua kiem nghiem vi sinh - Tieu Vietpepper",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-049", DocId: "DOC-049", ItemCode: "RM-209" },
    ],
  },
  {
    DocId: "DOC-050",
    PartnerId: "PARTNER-014",
    DocCode: "CO-RM214-2026",
    Version: "1",
    DocType: DocType.CO_KQKN,
    DocName: "Chung nhan C/O nguon goc - Ca com Phan Thiet",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-050", DocId: "DOC-050", ItemCode: "RM-214" },
    ],
  },

  // ==========================================
  // 11. KIEM_DICH (5 items)
  // ==========================================
  {
    DocId: "DOC-051",
    PartnerId: "PARTNER-002",
    DocCode: "KD-RM202-2026",
    Version: "1",
    DocType: DocType.KIEM_DICH,
    DocName: "Giay chung nhan kiem dich thuc vat - Ot tuoi",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-051", DocId: "DOC-051", ItemCode: "RM-202" },
    ],
  },
  {
    DocId: "DOC-052",
    PartnerId: "PARTNER-008",
    DocCode: "KD-RM204-2026",
    Version: "1",
    DocType: DocType.KIEM_DICH,
    DocName: "Giay kiem nghiem kiem dich - Toi Ly Son",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-052", DocId: "DOC-052", ItemCode: "RM-204" },
    ],
  },
  {
    DocId: "DOC-053",
    PartnerId: "PARTNER-010",
    DocCode: "KD-RM208-2026",
    Version: "1",
    DocType: DocType.KIEM_DICH,
    DocName: "Chung nhan kiem dich thuc vat - Ca chua Da Lat",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-053", DocId: "DOC-053", ItemCode: "RM-208" },
    ],
  },
  {
    DocId: "DOC-054",
    PartnerId: "PARTNER-012",
    DocCode: "KD-RM210-2026",
    Version: "1",
    DocType: DocType.KIEM_DICH,
    DocName: "Chung nhan kiem dich nong san - Hat sen tuoi",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-054", DocId: "DOC-054", ItemCode: "RM-210" },
    ],
  },
  {
    DocId: "DOC-055",
    PartnerId: "PARTNER-014",
    DocCode: "KD-RM214-2026",
    Version: "1",
    DocType: DocType.KIEM_DICH,
    DocName: "Giay kiem dich dong vat thuy san - Ca com",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-055", DocId: "DOC-055", ItemCode: "RM-214" },
    ],
  },

  // ==========================================
  // 12. OTHER (5 items)
  // ==========================================
  {
    DocId: "DOC-056",
    PartnerId: "PARTNER-001",
    DocCode: "OTH-RM201-2026",
    Version: "1",
    DocType: DocType.OTHER,
    DocName: "Cam ket chat luong nha cung cap - Hanh say",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-056", DocId: "DOC-056", ItemCode: "RM-201" },
    ],
  },
  {
    DocId: "DOC-057",
    PartnerId: "PARTNER-003",
    DocCode: "OTH-PG303-2026",
    Version: "1",
    DocType: DocType.OTHER,
    DocName: "Phieu danh gia ky thuat ben thu 3 - Vo chai PET",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-057", DocId: "DOC-057", ItemCode: "PG-303" },
    ],
  },
  {
    DocId: "DOC-058",
    PartnerId: "PARTNER-005",
    DocCode: "OTH-PG301-2026",
    Version: "1",
    DocType: DocType.OTHER,
    DocName: "Ban khai bao an toan nhua tiep xuc thuc pham",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.PENDING,
    DocItems: [
      { DocItemId: "DOC-ITEM-058", DocId: "DOC-058", ItemCode: "PG-301" },
    ],
  },
  {
    DocId: "DOC-059",
    PartnerId: "PARTNER-007",
    DocCode: "OTH-RM207-2026",
    Version: "1",
    DocType: DocType.OTHER,
    DocName: "Giay kiem dinh kho hang va dong goi - Duong Bien Hoa",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.APPROVED,
    DocItems: [
      { DocItemId: "DOC-ITEM-059", DocId: "DOC-059", ItemCode: "RM-207" },
    ],
  },
  {
    DocId: "DOC-060",
    PartnerId: "PARTNER-016",
    DocCode: "OTH-RM213-2026",
    Version: "1",
    DocType: DocType.OTHER,
    DocName: "Bao cao kiem nghiem chat luong - Acid Citric",
    FileURL: "/files/document_placeholder.pdf",
    ValidFrom: "2026-01-01",
    Status: DocStatus.REJECTED,
    DocItems: [
      { DocItemId: "DOC-ITEM-060", DocId: "DOC-060", ItemCode: "RM-213" },
    ],
  },
];
