import { Item } from "../features/item/types";
import { ItemType } from "../enums";

export const mockItems: Item[] = [
  // 1-12
  {
    ItemCode: "FG-001",
    ItemName: "Nước tương Chinsu Tỏi Ớt 250ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-002",
    ItemName: "Mì Omachi Xốt Bò Hầm 80g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    VersionERP: 2,
    VersionStorage: 2,
  },
  {
    ItemCode: "FG-003",
    ItemName: "Nước mắm Nam Ngư Đệ Nhị 900ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-101",
    ItemName: "Nước cốt hầm xương bò đặc chế",
    ItemType: ItemType.IP,
    UoM: "Lít",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-102",
    ItemName: "Bột gia vị mì ăn liền dạng bán thành phẩm",
    ItemType: ItemType.IP,
    UoM: "Kg",
    VersionERP: 3,
    VersionStorage: 2,
  },
  {
    ItemCode: "IP-103",
    ItemName: "Mỡ heo sơ chế",
    ItemType: ItemType.IP,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-201",
    ItemName: "Hành lá sấy khô nguyên chất",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 2,
    VersionStorage: 2,
  },
  {
    ItemCode: "RM-202",
    ItemName: "Ớt tươi chỉ thiên",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-203",
    ItemName: "Bột mì cao cấp nhập khẩu",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    VersionERP: 4,
    VersionStorage: 3,
  },
  {
    ItemCode: "PG-301",
    ItemName: "Màng co OPP bọc gói mì Omachi",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-302",
    ItemName: "Thùng carton 30 gói mì Omachi",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-303",
    ItemName: "Vỏ chai PET đựng nước tương 250ml",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 2,
    VersionStorage: 2,
  },

  // 13-24
  {
    ItemCode: "FG-004",
    ItemName: "Tương ớt Chinsu Siêu Cay 250g",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-005",
    ItemName: "Mì Kokomi Đại 90g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    VersionERP: 2,
    VersionStorage: 2,
  },
  {
    ItemCode: "FG-006",
    ItemName: "Nước khoáng thiên nhiên Vĩnh Hảo 500ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-104",
    ItemName: "Nước cốt ớt lên men tự nhiên",
    ItemType: ItemType.IP,
    UoM: "Lít",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-105",
    ItemName: "Gói súp gia vị Kokomi bán thành phẩm",
    ItemType: ItemType.IP,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-204",
    ItemName: "Tỏi Lý Sơn sơ chế sạch vỏ",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-205",
    ItemName: "Bột ớt cay chỉ thiên sấy khô",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 2,
    VersionStorage: 2,
  },
  {
    ItemCode: "RM-206",
    ItemName: "Muối tinh khiết sấy khô công nghiệp",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-207",
    ItemName: "Đường tinh luyện Biên Hòa thượng hạng",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-304",
    ItemName: "Vỏ chai PET đựng tương ớt 250g",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-305",
    ItemName: "Màng co OPP Kokomi",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-306",
    ItemName: "Thùng carton 30 gói mì Kokomi",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },

  // 25-48
  {
    ItemCode: "FG-007",
    ItemName: "Tương cà Chinsu thơm ngọt 250g",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-008",
    ItemName: "Mì Kokomi Xốt Cay 90g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-009",
    ItemName: "Nước mắm Nam Ngư Nhãn Vàng 650ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-010",
    ItemName: "Cháo sen bát bảo Minh Trung 365g",
    ItemType: ItemType.FG,
    UoM: "Lon",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-011",
    ItemName: "Hạt nêm Chinsu Ngọt Tôm Thơm Thịt 400g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "FG-012",
    ItemName: "Nước tăng lực Compact Hoa Anh Đào 330ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    VersionERP: 2,
    VersionStorage: 2,
  },

  {
    ItemCode: "IP-106",
    ItemName: "Nước cốt cà chua cô đặc",
    ItemType: ItemType.IP,
    UoM: "Lít",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-107",
    ItemName: "Hành tỏi băm nhuyễn xào thơm gia vị",
    ItemType: ItemType.IP,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-108",
    ItemName: "Dịch cá cơm nguyên chất thủy phân",
    ItemType: ItemType.IP,
    UoM: "Lít",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-109",
    ItemName: "Hạt sen hầm đường phèn bán thành phẩm",
    ItemType: ItemType.IP,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "IP-110",
    ItemName: "Xốt gia vị hạt nêm sấy chân không",
    ItemType: ItemType.IP,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },

  {
    ItemCode: "RM-208",
    ItemName: "Cà chua tươi hữu cơ Lâm Đồng",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-209",
    ItemName: "Hạt tiêu đen Phú Quốc chín tự nhiên",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-210",
    ItemName: "Hạt sen tươi Đồng Tháp loại A",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-211",
    ItemName: "Bột tôm sú sấy khô nguyên chất",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-212",
    ItemName: "Hương hoa anh đào tự nhiên nhập khẩu",
    ItemType: ItemType.RM,
    UoM: "Lít",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-213",
    ItemName: "Acid citric chất điều chỉnh độ acid",
    ItemType: ItemType.RM,
    UoM: "Kg",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "RM-214",
    ItemName: "Cá cơm tươi đại dương Phan Thiết",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    VersionERP: 2,
    VersionStorage: 1,
  },

  {
    ItemCode: "PG-307",
    ItemName: "Vỏ chai PET tương cà 250g",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-308",
    ItemName: "Nắp chai nhựa có vòi cắt Chinsu",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-309",
    ItemName: "Lon nhôm hai mảnh đựng cháo 365g",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-310",
    ItemName: "Màng nhôm phức hợp túi hạt nêm 400g",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-311",
    ItemName: "Vỏ chai nhựa PET Compact 330ml",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
  {
    ItemCode: "PG-312",
    ItemName: "Thùng carton đựng nước tăng lực Compact",
    ItemType: ItemType.PG,
    UoM: "Cái",
    VersionERP: 1,
    VersionStorage: 1,
  },
];
