import { ItemVersion } from "../features/item/types";
import { ItemType } from "../enums";

export const mockItemVersions: ItemVersion[] = [
  {
    ItemVersionId: "IV-001-V1",
    ItemCode: "FG-001",
    Version: 1,
    ItemName: "Nước tương Chinsu Tỏi Ớt 250ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-05-31",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-15 10:00",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-002-V1",
    ItemCode: "FG-002",
    Version: 1,
    ItemName: "Mì Omachi Xốt Bò Hầm 80g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-02-01",
    ValidTo: "2026-06-30",
    ModifiedBy: "sysadmin@masan.com.vn",
    ModifiedAt: "2026-01-10 14:30",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-002-V2",
    ItemCode: "FG-002",
    Version: 2,
    ItemName: "Mì Omachi Xốt Bò Hầm Thượng Hạng 80g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    Substitute: "Thay RM-201 bằng RM-201-V2 (hành sấy)",
    Status: "APPROVED",
    ValidFrom: "2026-07-01",
    ValidTo: null,
    ModifiedBy: "qa_manager@masan.com.vn",
    ModifiedAt: "2026-06-20 09:15",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-102-V1",
    ItemCode: "IP-102",
    Version: 1,
    ItemName: "Bột gia vị mì ăn liền dạng bán thành phẩm",
    ItemType: ItemType.IP,
    UoM: "Kg",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-04-30",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-20 11:00",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-102-V2",
    ItemCode: "IP-102",
    Version: 2,
    ItemName: "Bột gia vị mì ăn liền dạng bán thành phẩm cao cấp",
    ItemType: ItemType.IP,
    UoM: "Kg",
    Substitute: "Thay RM-201 bằng RM-204 (tỏi sấy)",
    Status: "APPROVED",
    ValidFrom: "2026-05-01",
    ValidTo: null,
    ModifiedBy: "researcher@masan.com.vn",
    ModifiedAt: "2026-04-15 08:00",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-102-V3-ERP",
    ItemCode: "IP-102",
    Version: 3,
    ItemName: "Bột gia vị mì ăn liền bán thành phẩm đặc biệt",
    ItemType: ItemType.IP,
    UoM: "Kg",
    Substitute: "Thay RM-206 bằng RM-206-IOT (muối iot)",
    Status: "PENDING",
    ValidFrom: "2026-07-10",
    ValidTo: null,
    ModifiedBy: "erp_system",
    ModifiedAt: "2026-07-10 17:00",
    IsSyncERP: false,
  },
  {
    ItemVersionId: "IV-201-V1",
    ItemCode: "RM-201",
    Version: 1,
    ItemName: "Hành lá sấy khô nguyên chất",
    ItemType: ItemType.RM,
    UoM: "Kg",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-04-30",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-10 14:00",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-201-V2",
    ItemCode: "RM-201",
    Version: 2,
    ItemName: "Hành lá sấy khô nguyên chất sạch chuẩn",
    ItemType: ItemType.RM,
    UoM: "Kg",
    Substitute: "Có thể thay bằng hành tươi",
    Status: "APPROVED",
    ValidFrom: "2026-05-01",
    ValidTo: null,
    ModifiedBy: "qa_manager@masan.com.vn",
    ModifiedAt: "2026-04-20 09:30",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-203-V1",
    ItemCode: "RM-203",
    Version: 1,
    ItemName: "Bột mì cao cấp nhập khẩu",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-03-31",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-12 15:00",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-203-V2",
    ItemCode: "RM-203",
    Version: 2,
    ItemName: "Bột mì cao cấp nhập khẩu tăng Gluten",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    Substitute: "Thay bột mì nội địa nếu khan hàng",
    Status: "APPROVED",
    ValidFrom: "2026-04-01",
    ValidTo: "2026-07-31",
    ModifiedBy: "sysadmin@masan.com.vn",
    ModifiedAt: "2026-03-25 10:45",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-203-V3",
    ItemCode: "RM-203",
    Version: 3,
    ItemName: "Bột mì cao cấp nhập khẩu chuẩn cao",
    ItemType: ItemType.RM,
    UoM: "Tấn",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-08-01",
    ValidTo: null,
    ModifiedBy: "qa_manager@masan.com.vn",
    ModifiedAt: "2026-07-28 11:20",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-303-V1",
    ItemCode: "PG-303",
    Version: 1,
    ItemName: "Vỏ chai PET đựng nước tương 250ml",
    ItemType: ItemType.PG,
    UoM: "Cái",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-05-31",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-15 16:30",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-303-V2",
    ItemCode: "PG-303",
    Version: 2,
    ItemName: "Vỏ chai PET đựng nước tương 250ml (Cải tiến nắp chai)",
    ItemType: ItemType.PG,
    UoM: "Cái",
    Substitute: "Thay nắp vòi cắt Chinsu",
    Status: "APPROVED",
    ValidFrom: "2026-06-01",
    ValidTo: null,
    ModifiedBy: "sysadmin@masan.com.vn",
    ModifiedAt: "2026-05-22 13:40",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-005-V1",
    ItemCode: "FG-005",
    Version: 1,
    ItemName: "Mì Kokomi Đại 90g",
    ItemType: ItemType.FG,
    UoM: "Gói",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-05-31",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-22 09:15",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-005-V2",
    ItemCode: "FG-005",
    Version: 2,
    ItemName: "Mì Kokomi Đại 90g (Bao bì mới)",
    ItemType: ItemType.FG,
    UoM: "Gói",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-06-01",
    ValidTo: null,
    ModifiedBy: "qa_manager@masan.com.vn",
    ModifiedAt: "2026-05-28 10:20",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-205-V1",
    ItemCode: "RM-205",
    Version: 1,
    ItemName: "Bột ớt cay chỉ thiên sấy khô",
    ItemType: ItemType.RM,
    UoM: "Kg",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-05-31",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-18 10:50",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-205-V2",
    ItemCode: "RM-205",
    Version: 2,
    ItemName: "Bột ớt cay chỉ thiên sấy khô cao cấp",
    ItemType: ItemType.RM,
    UoM: "Kg",
    Substitute: "Có thể thay bằng ớt tươi chỉ thiên",
    Status: "APPROVED",
    ValidFrom: "2026-06-01",
    ValidTo: null,
    ModifiedBy: "sysadmin@masan.com.vn",
    ModifiedAt: "2026-05-24 14:15",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-012-V1",
    ItemCode: "FG-012",
    Version: 1,
    ItemName: "Nước tăng lực Compact Hoa Anh Đào 330ml",
    ItemType: ItemType.FG,
    UoM: "Chai",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-01-01",
    ValidTo: "2026-05-31",
    ModifiedBy: "admin@masan.com.vn",
    ModifiedAt: "2025-12-25 11:20",
    IsSyncERP: true,
  },
  {
    ItemVersionId: "IV-012-V2",
    ItemCode: "FG-012",
    Version: 2,
    ItemName: "Nước tăng lực Compact Hoa Anh Đào 330ml (Cải tiến hương liệu)",
    ItemType: ItemType.FG,
    UoM: "Chai",
    Substitute: "Không có",
    Status: "APPROVED",
    ValidFrom: "2026-06-01",
    ValidTo: null,
    ModifiedBy: "qa_manager@masan.com.vn",
    ModifiedAt: "2026-05-29 15:30",
    IsSyncERP: true,
  },
];
