export const ENTITY_METADATA_KEY = 'custom-repo:entity';
export const DEFAULT_CONNECTION_NAME = 'default';
export const DEF_REPO_DYNAMIC_PROVIDERS = 'DEF_REPO_DYNAMIC_PROVIDERS';
export const DEF_REPOSITORY_OPTIONS = 'DEF_REPOSITORY_OPTIONS';
